[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 20.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
opacity = 0.6

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[env]
TERM = "xterm-256color"
